# Command to use for server transfer (default: apenet)
command: apenet

# Server configurations
servers:
  lobby:
    host: lobby.example.com
    port: 25565
  survival:
    host: survival.example.com
    port: 25566
  creative:
    host: creative.example.com
    port: 25567